from __future__ import annotations

GENE_PANELS: dict[str, list[str]] = {
    "panglial_connexins": ["GJC2", "GJB1", "GJC3", "GJA1", "GJB6", "GJD2"],
    "oligodendrocyte_identity": [
        "MBP",
        "MOG",
        "PLP1",
        "MAG",
        "CNP",
        "SOX10",
        "OLIG2",
        "NKX2-2",
        "MYRF",
        "PPARGC1A",
    ],
    "astrocyte_identity": ["GFAP", "AQP4", "ALDH1L1", "SLC1A2", "SLC1A3"],
    "mitochondrial_oxphos": [
        "NDUFA9",
        "NDUFS1",
        "NDUFS3",
        "NDUFB8",
        "SDHA",
        "SDHB",
        "UQCRC1",
        "UQCRC2",
        "COX4I1",
        "COX5A",
        "COX6A1",
        "ATP5F1A",
        "ATP5F1B",
        "ATP5MC1",
    ],
    "mitochondrial_membrane_transport": [
        "VDAC1",
        "VDAC2",
        "VDAC3",
        "TOMM20",
        "TOMM40",
        "TOMM70",
        "SLC25A4",
        "SLC25A5",
        "SLC25A3",
        "MCU",
        "MICU1",
    ],
    "mitochondrial_dynamics": ["MFN1", "MFN2", "OPA1", "DNM1L", "FIS1"],
    "mitochondrial_biogenesis": ["PPARGC1A", "TFAM", "NRF1", "NFE2L2"],
    "mitophagy_stress": ["PINK1", "PRKN", "BNIP3", "BNIP3L", "HIF1A", "IL6", "TNF", "SIRT1"],
    "mitochondrial_trafficking": ["RHOT1", "RHOT2", "TRAK1", "TRAK2", "KIF5B", "DYNC1H1"],
    "metabolic_coupling": ["SLC16A1", "SLC16A3", "LDHA", "LDHB"],
    "cx47_upstream_regulators": ["PRKCA", "MAPK1", "MAPK3", "CAMK2A"],
    "inflammatory_cytokines": ["TNF", "IL1B", "IL6", "CCL2", "CXCL10", "CSF2"],
    "microglial_activation": ["NOS2", "HLA-DRA", "CD68", "ITGAM", "AIF1", "C1QA", "C3"],
    "er_stress_upr": ["ERP29", "ATF4", "XBP1", "DDIT3", "HSPA5", "EIF2AK3"],
    "ion_homeostasis": ["KCNJ10", "ATP1A2", "SLC1A2", "SLC1A3"],
    "lymphatic_endothelial": ["PROX1", "PECAM1", "FOXC2", "GATA2", "VEGFC", "PDPN", "FLT4", "ANGPT2", "LYVE1", "KDR"],
    "lymphatic_barrier": ["TJP1", "CLDN5", "OCLN", "CDH5"],
    "lipid_metabolism": [
        "ABCA1",
        "ABCG1",
        "LDLR",
        "APOE",
        "LPL",
        "SREBF2",
        "HMGCR",
        "FASN",
        "CD36",
        "TREM2",
        "PLIN2",
        "CERS2",
        "UGT8",
        "SCD1",
    ],
    "bbb_related": ["CLDN5", "OCLN", "TJP1", "PECAM1", "AQP4", "SLC1A2", "KCNJ10", "ATP1A2"],
    # --- Q3: reactive glia ---
    "a1_reactive_astrocytes": ["TNF", "IL1A", "C1QA", "C3"],
    # --- Q4: transglial mitochondrial communication ---
    "vesicle_trafficking": [
        "SNAP23", "SNAPC5", "SNAPIN",
        "VAMP2", "VAMP3", "VAMP4", "VAMP5", "VAMP7", "VAMP8",
        "STX4", "STXBP3", "STXBP6",
    ],
    "ev_markers": ["CD9", "CD37", "CD63", "CD81", "CD82", "FLOT1"],
    "tnt_core": ["TNFAIP2", "RALA", "RALBP1", "RALGAPA1", "RALGAPB", "RALGDS"],
    "actin_cytoskeleton": ["ACTB", "ACTG1", "ACTN4", "CDC42", "RAC1", "WASL", "ACTR2", "ACTR3"],
    "mdv_lysosomal": ["LAMP1", "LAMP2", "RAB7", "SNX9"],
    "mdv_peroxisomal": ["PEX3", "PEX14", "PEX16", "PEX19", "PEX5"],
    "autophagy_stress": ["FUNDC1", "ATG4D", "ATG9A", "ATG7"],
    # --- Q5: lipid metabolism and glymphatic ---
    "myelin_lipid_synthesis": ["CERS2", "UGT8", "SCD1"],
}
